### ISSUE TITLE
Illegal instruction: 4

### ISSUE THREAD

**Issue by altuzar** [nickjj/build-a-saas-app-with-flask#26]
Trying to install the project, I get:

```
# docker-compose up
Illegal instruction: 4
```

For sure is only that I'm a complete Docker newbie. Probably I didn't "Edit docker-compose.yml and setup a local volume for Postgres/Redis" properly, as I just installed Docker from the Docker site installer for Mac OSX and executed the "Docker Quickstart Terminal" binary. 

Ty!

**Comment by nickjj** [comment]
Hi, can you paste in your entire `docker-compose.yml` file. Feel free to omit any passwords and secure tokens before pasting it in here.

**Comment by altuzar** [comment]
Hi. My `docker-compose.yml` file is the same one in the git repo. As I told, complete Docker newbie here. _Shame on me hehe_. I've used vms a long time but not much Docker. Imagine I have to create a docker volume, install postgresql and redis there and maybe some other deps. 

It starts with:

```
postgres:
  image: postgres:9.4.3
  environment:
    POSTGRES_USER: catwatch
    POSTGRES_PASSWORD: bestpassword
  ports:
    - 5432:5432
  volumes:
    - ~/.docker-volumes/catwatch/postgresql/data:/var/lib/postgresql/data
```
